# Capstone — mirrors your deployed research paper

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/flyrank-bih/flyrank-ml-internship-starter/blob/main/work/notebooks/capstone.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Question
**Lane:** CTR / Engagement Opportunity Scoring (official lane 4 of 4).

**Question:** Among pages already ranking, which ones under-earn clicks for their position, and
what's the highest-leverage fix? Full framing: `research_question_framing.md`.

In [1]:
print("Lane: CTR / Engagement Opportunity Scoring")
print("Full framing committed at: research_question_framing.md, ml_task_framing.md")

Lane: CTR / Engagement Opportunity Scoring
Full framing committed at: research_question_framing.md, ml_task_framing.md


## 2. Data

FlyRank `internship-warehouse` on Hugging Face: `fact_content_daily_performance` (78.8M rows)
joined to `dim_content` (519,606 rows), filtered to March 2026. Grain verified (zero violations).
Full contract, queries, and leakage trap: `w03_data_contract.ipynb`.

In [2]:
print("176,568 content items | 46 of 104 clients represented | March 2026")
print("Leakage trap: honest R2=0.002 vs leaky R2=1.000 (w03_data_contract.ipynb)")

176,568 content items | 46 of 104 clients represented | March 2026
Leakage trap: honest R2=0.002 vs leaky R2=1.000 (w03_data_contract.ipynb)


## 3. Methodology
Position-tier CTR baseline (signal CONFIRMED, w04_baseline_score.ipynb), compared against a
Random Forest validated with 5-fold GroupKFold by client (zero train/test client overlap,
w05_model.ipynb). Honest-split before/after and a leakage audit followed in w06_validation_audit.ipynb.

In [3]:
print("Baseline: mean CTR per position tier (1_top_3 ... 5_deep)")
print("Model: RandomForestRegressor, 5-fold GroupKFold by client_hash_id")

Baseline: mean CTR per position tier (1_top_3 ... 5_deep)
Model: RandomForestRegressor, 5-fold GroupKFold by client_hash_id


## 4. Results (vs baseline)

| Method | MAE | Spearman |
|---|---|---|
| Baseline (position-tier) | 0.008499 | 0.166 |
| Random Forest | 0.007749 | 0.057 |

Random Forest: 8.8% lower MAE, but weaker rank correlation. Since the deliverable is a ranked
list, the baseline's stronger ranking performance is the decision-relevant result.


In [4]:
import pandas as pd
pd.DataFrame([
    ['baseline_position_tier', 0.008499, 0.166072],
    ['random_forest', 0.007749, 0.057163],
], columns=['method','MAE','spearman'])

,method,MAE,spearman
0,baseline_position_tier,0.008499,0.166072
1,random_forest,0.007749,0.057163


## 5. Limitations
No causal claims. Single month (March 2026) only. 58 of 104 clients unrepresented. A quantified,
small (0.1%) survivorship gap from current-snapshot publish/delete filters. Full list: paper's
Limitations section and `w06_validation_audit.ipynb`.

In [5]:
# Limitations are prose-only for this section — no query needed here.
print("See w06_validation_audit.ipynb for the leakage audit and survivorship quantification.")

See w06_validation_audit.ipynb for the leakage audit and survivorship quantification.


## 6. Ranked recommendations
Five archetypes built on the baseline (since it outranks the model): Protect (19,147), Improve
(61,481), Refresh candidate (11,335), Monitor–low data (33,465), Low priority (51,140). Full
logic, human-review rules, and exports: `w07_action_playbook.ipynb`.

In [7]:
print("Actionable queue (Improve + Refresh candidate): 72,816 pages")
print("Cannibalization check: 101 client x tier groups with 5+ flagged pages, top case = 10,073")

Actionable queue (Improve + Refresh candidate): 72,816 pages
Cannibalization check: 101 client x tier groups with 5+ flagged pages, top case = 10,073


## 7. Artifacts the paper embeds

This notebook is the working index. The polished, deployed version — with all charts, the
leakage-demonstration signature figure, and full prose — lives at:
https://adeenasaleem.github.io/flyrank-ml-internship/

In [8]:
print("Deployed paper: https://adeenasaleem.github.io/flyrank-ml-internship/")

Deployed paper: https://adeenasaleem.github.io/flyrank-ml-internship/


## 8. Tell the story (ML-12)

### 5-minute demo outline

**Question (30s).** Among pages already ranking, which under-earn clicks for their position —
and what's the highest-leverage fix?

**Method (1 min).** Built a position-tier CTR baseline from real March 2026 data, then trained
a Random Forest to see if added features could beat it — validated with a client-grouped split
so no client's pages ever leaked between train and test.

**One chart (1 min).** The leakage-demonstration figure: a toy model's R² jumped from 0.002 to
1.000 the moment a disguised copy of the target was added as a "feature" — the clearest possible
picture of why validation discipline matters before trusting any result that follows.

**One honest result (1.5 min).** The Random Forest had 8.8% lower prediction error than the
baseline — but the baseline ranked pages *better* (Spearman 0.166 vs 0.057). Since the actual
deliverable is a ranked list, the simple lookup table wins on the metric that matters. That's
the headline finding, not a footnote.

**One recommendation (1 min).** Built on the baseline that actually works: a five-archetype
playbook flagging 72,816 actionable pages, with real limits attached — including one client
alone having 10,073 pages flagged in a single position tier, meaning a client-level review
beats page-by-page edits at that scale.

---

### Shareable cut 1 — social post (methodology-focused)

> Trained a Random Forest to find underperforming pages in 176K real search-console rows.
> It beat a simple position-tier lookup table on prediction error — and lost to it on ranking
> quality, which is the metric that actually mattered for the task. Reporting the model that
> "lost" felt more honest than reporting the one metric that made it look like it won. Full
> writeup, real numbers, real leakage test included: [deployed paper link]

### Shareable cut 2 — 3-sentence employer summary

> I built a CTR-opportunity scoring system on FlyRank's 79-million-row real search data,
> comparing a trained Random Forest against a transparent baseline under a client-grouped
> validation split. The baseline outranked the model on the metric that mattered for the actual
> deliverable — a finding I reported honestly rather than picking the metric that flattered the
> more complex approach. The result shipped as a five-archetype action playbook with human-review
> rules, grounded in a real 10,073-page finding, not a theoretical caveat.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.
- [ ] My deployed paper has **all 9 sections** — including the **Abstract** at the top and **Acknowledgments & data credit** (the https://flyrank.ai link) at the bottom.
- [ ] **ML-12 done in this notebook's closing cells:** 5-minute demo outline + a social-post cut + a 3-sentence employer-facing summary.
